version: '3.8'

services:
  web:
    build: .
    container_name: lecta-web
    env_file:
      - ../.env
    networks:
      - lecta_net
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: lecta-db
    env_file:
      - ../.env
    image: postgres:15
    networks:
      - lecta_net
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

networks:
  lecta_net:
    name: lecta-network